# Generated by Django 5.0.6 on 2024-05-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingTariffs',
            fields=[
                ('packagingtariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('availeble', models.BooleanField(blank=True, default=False, null=True)),
                ('setup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_per_100kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_weight_packaging_unit_kg', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'packagingtariffs',
                'verbose_name_plural': 'packagingtariff',
            },
        ),
        migrations.CreateModel(
            name='ProducerContacts',
            fields=[
                ('producercontact_id', models.AutoField(primary_key=True, serialize=False)),
                ('producercontact', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=25)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('e_mail_personal', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'producercontacts',
                'verbose_name_plural': 'producercontact',
            },
        ),
        migrations.CreateModel(
            name='ProducerProductOfferings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('availeble', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportTariffs',
            fields=[
                ('transporttariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_value', models.BooleanField(default=True)),
                ('availeble', models.BooleanField(blank=True, default=False, null=True)),
                ('setup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_per_100kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'transporttariffs',
                'verbose_name_plural': 'transporttariff',
            },
        ),
        migrations.CreateModel(
            name='EnhancementTariffs',
            fields=[
                ('enhancementtariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_value', models.BooleanField(default=True)),
                ('availeble', models.BooleanField(blank=True, default=False, null=True)),
                ('setup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('minimum_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('production_cost_1000sheets', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_sheet_width', models.PositiveIntegerField(default=0)),
                ('max_sheet_height', models.PositiveIntegerField(default=0)),
                ('enhancement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='methods.enhancementoptions')),
            ],
            options={
                'verbose_name': ' enhancementtariffs',
                'verbose_name_plural': 'enhancementtariff',
            },
        ),
    ]
