# Generated by Django 5.1.1 on 2024-11-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enhancementtariffs',
            options={'verbose_name': 'enhancementtariffs', 'verbose_name_plural': 'enhancementtariff'},
        ),
    ]
