# Generated by Django 5.1.1 on 2024-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_alter_enhancementtariffs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerproductofferings',
            name='max_product_size',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='producerproductofferings',
            name='max_product_volume',
            field=models.FloatField(default=100000, null=True),
        ),
        migrations.AddField(
            model_name='producerproductofferings',
            name='min_product_size',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='producerproductofferings',
            name='min_product_volume',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
