# Generated by Django 5.1.1 on 2024-12-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_producerproductofferings_max_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerproductofferings',
            name='max_product_volume',
            field=models.PositiveIntegerField(default=100000, null=True),
        ),
    ]
