# Generated by Django 5.0.6 on 2024-05-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('profileuseraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbrand',
            name='language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages'),
        ),
        migrations.AddField(
            model_name='paperbrand',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
        migrations.AddField(
            model_name='paperbrandreference',
            name='language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages'),
        ),
        migrations.AddField(
            model_name='papercatalog',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
        migrations.AddField(
            model_name='paperweights',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
        migrations.AddField(
            model_name='producerpapercategory',
            name='language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages'),
        ),
        migrations.AddField(
            model_name='producerpapercategory',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
    ]
