# Generated by Django 5.0.6 on 2024-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papercategoryreference',
            name='brochures_booklet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='papercategoryreference',
            name='brochures_cover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='papercategoryreference',
            name='folders_cover',
            field=models.BooleanField(default=True),
        ),
    ]
