# Generated by Django 5.1.1 on 2024-12-02 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
        ('profileuseraccount', '0006_remove_producers_brandportal_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papercatalog',
            name='source_id',
        ),
        migrations.CreateModel(
            name='EnvelopeCategory',
            fields=[
                ('envelope_category_brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('envelope_category', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers')),
            ],
            options={
                'verbose_name': 'envelope_brand',
                'verbose_name_plural': 'envelope_brands',
            },
        ),
        migrations.CreateModel(
            name='EnvelopeCatalog',
            fields=[
                ('envelope_catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=250)),
                ('supplier_number', models.CharField(max_length=250)),
                ('env_category_name', models.CharField(max_length=250)),
                ('env_paper', models.CharField(blank=True, max_length=250)),
                ('env_color', models.CharField(blank=True, max_length=250, null=True)),
                ('env_interior', models.CharField(blank=True, max_length=250, null=True)),
                ('env_size', models.CharField(blank=True, max_length=250)),
                ('env_weight_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('env_die_cut', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('env_closure', models.CharField(blank=True, max_length=250)),
                ('env_window_orientation', models.CharField(blank=True, max_length=250)),
                ('env_window_size', models.CharField(blank=True, max_length=250)),
                ('env_window_position', models.CharField(blank=True, max_length=250)),
                ('FSC', models.BooleanField(default=True)),
                ('env_size_close_cut', models.CharField(blank=True, max_length=500, null=True)),
                ('env_material_color', models.CharField(blank=True, max_length=500, null=True)),
                ('env_window', models.CharField(blank=True, max_length=500, null=True)),
                ('envelopes_per_pack', models.PositiveIntegerField(blank=True, null=True)),
                ('price_1000_envelopes', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('upload_date', models.DateField(null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=500)),
                ('producer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers')),
                ('env_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.envelopecategory')),
            ],
            options={
                'verbose_name': 'paper',
                'verbose_name_plural': 'papers',
            },
        ),
    ]
