# Generated by Django 5.1.1 on 2024-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_papercatalog_source_id_envelopecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopecatalog',
            name='env_die_cut',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
