# Generated by Django 5.0.6 on 2024-05-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_papercategoryreference_brochures_booklet_and_more'),
        ('profileuseraccount', '0004_remove_members_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCategories',
            fields=[
                ('papercategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('papercategory', models.CharField(blank=True, max_length=250)),
                ('folders_cover', models.BooleanField(default=True)),
                ('brochures_booklet', models.BooleanField(default=True)),
                ('brochures_cover', models.BooleanField(default=True)),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers')),
            ],
            options={
                'verbose_name': 'papercategory',
                'verbose_name_plural': 'papercategories',
            },
        ),
        migrations.RenameModel(
            old_name='PaperBrand',
            new_name='PaperBrands',
        ),
        migrations.DeleteModel(
            name='PaperCategoryReference',
        ),
        migrations.DeleteModel(
            name='ProducerPaperCategory',
        ),
    ]
