# Generated by Django 5.1.1 on 2024-12-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_envelopecatalog_env_die_cut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envelopecategory',
            options={'verbose_name': 'envelope_category', 'verbose_name_plural': 'envelope_categories'},
        ),
        migrations.RenameField(
            model_name='envelopecategory',
            old_name='envelope_category_brand_id',
            new_name='envelope_category_id',
        ),
        migrations.RenameField(
            model_name='envelopecategory',
            old_name='envelope_category',
            new_name='envelope_category_name',
        ),
    ]
