# Generated by Django 5.0.6 on 2024-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_papercategories_rename_paperbrand_paperbrands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperbrandreference',
            name='language',
        ),
        migrations.RemoveField(
            model_name='paperbrands',
            name='language',
        ),
        migrations.RemoveField(
            model_name='papercategories',
            name='brochures_booklet',
        ),
        migrations.RemoveField(
            model_name='papercategories',
            name='brochures_cover',
        ),
        migrations.RemoveField(
            model_name='papercategories',
            name='folders_cover',
        ),
        migrations.AddField(
            model_name='papercatalog',
            name='singe_sided',
            field=models.BooleanField(default=False),
        ),
    ]
