# Generated by Django 5.1.1 on 2024-12-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_envelopecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envelopecategory',
            old_name='envelope_category_id',
            new_name='env_category_id',
        ),
        migrations.RenameField(
            model_name='envelopecategory',
            old_name='envelope_category_name',
            new_name='env_category_name',
        ),
    ]
