# Generated by Django 5.0.6 on 2024-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_remove_paperbrandreference_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papercategories',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='paperweights',
            name='producer',
        ),
        migrations.AddField(
            model_name='papercatalog',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PaperBrands',
        ),
        migrations.DeleteModel(
            name='PaperCategories',
        ),
        migrations.DeleteModel(
            name='PaperWeights',
        ),
    ]
