# Generated by Django 5.0.6 on 2024-05-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_papercategories_producer_and_more'),
        ('profileuseraccount', '0004_remove_members_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperbrandreference',
            name='brochures_cover',
        ),
        migrations.RemoveField(
            model_name='paperbrandreference',
            name='brochures_interior',
        ),
        migrations.RemoveField(
            model_name='paperbrandreference',
            name='folders',
        ),
        migrations.AddField(
            model_name='paperbrandreference',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
    ]
