# Generated by Django 5.1.1 on 2024-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_rename_envelope_category_id_envelopecategory_env_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopecatalog',
            name='env_height_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envelopecatalog',
            name='env_width_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
