# Generated by Django 5.0.6 on 2024-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_remove_paperbrandreference_brochures_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papercatalog',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
