# Generated by Django 5.0.6 on 2024-05-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('profileuseraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingmachines',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
        migrations.AddField(
            model_name='cuttingmachines',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
        migrations.AddField(
            model_name='foldingmachines',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
        migrations.AddField(
            model_name='foldingtypes',
            name='language',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages'),
        ),
        migrations.AddField(
            model_name='foldingmachines',
            name='foldingtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.foldingtypes'),
        ),
        migrations.AddField(
            model_name='generalcalculationsettings',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
        migrations.AddField(
            model_name='printers',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuseraccount.producers'),
        ),
    ]
