# Generated by Django 5.0.6 on 2024-06-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculations',
            name='offer',
        ),
    ]
