# Generated by Django 5.0.6 on 2024-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('requester', models.CharField(blank=True, max_length=200, null=True)),
                ('offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_1000extra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producer_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('producer_quote', models.CharField(blank=True, max_length=200, null=True)),
                ('producer_notes', models.TextField(blank=True, max_length=2500)),
                ('offer_key', models.PositiveIntegerField(blank=True, null=True)),
                ('offer_key_test', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_key', models.PositiveIntegerField(blank=True, null=True)),
                ('doc_name', models.TextField(blank=True, max_length=250)),
                ('doc_uploaded', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'offers',
                'verbose_name_plural': 'offer',
            },
        ),
        migrations.CreateModel(
            name='Offerstatus',
            fields=[
                ('offerstatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('offerstatus', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'offerstatus',
                'verbose_name_plural': 'offerstatus',
            },
        ),
    ]
