# Generated by Django 5.0.6 on 2024-05-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='offer_1000extra',
            new_name='offer1000extra',
        ),
    ]
