# Generated by Django 5.0.6 on 2024-06-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0003_remove_calculations_offer'),
        ('offers', '0003_rename_offer_1000extra_offers_offer1000extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculations.calculations'),
        ),
    ]
