# Generated by Django 5.0.6 on 2024-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('blacklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('blacklist_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'blacklist_texts',
                'verbose_name_plural': 'blacklist_text',
            },
        ),
        migrations.CreateModel(
            name='BrandPortalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandportal', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_payoff', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=400, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=400, null=True)),
                ('loc_order_supply', models.CharField(blank=True, max_length=400, null=True)),
                ('doc_loc_offer_1', models.CharField(blank=True, max_length=400, null=True)),
                ('doc_loc_offer_2', models.CharField(blank=True, max_length=400, null=True)),
                ('doc_loc_offer_3', models.CharField(blank=True, max_length=400, null=True)),
                ('doc_loc_offer_4', models.CharField(blank=True, max_length=400, null=True)),
                ('doc_loc_offer_5', models.CharField(blank=True, max_length=400, null=True)),
                ('doc_loc_offer_6', models.CharField(blank=True, max_length=400, null=True)),
                ('img_bg_loc_inlog', models.CharField(blank=True, max_length=400, null=True)),
                ('img_loc_logo', models.CharField(blank=True, max_length=400, null=True)),
                ('img_loc_logo_lg', models.CharField(blank=True, max_length=400, null=True)),
                ('img_loc_logo_sm', models.CharField(blank=True, max_length=400, null=True)),
                ('img_loc_sheets', models.CharField(blank=True, max_length=400, null=True)),
                ('img_loc_plano', models.PositiveIntegerField(default=1)),
                ('img_loc_folders', models.PositiveIntegerField(default=2)),
                ('img_loc_selfcovers', models.PositiveIntegerField(default=3)),
                ('img_loc_brochures', models.PositiveIntegerField(default=4)),
                ('img_loc_books', models.PositiveIntegerField(default=5)),
                ('brandcolor_bg', models.CharField(blank=True, max_length=50, null=True)),
                ('brandcolor_font', models.CharField(blank=True, max_length=50, null=True)),
                ('brandcolor_header', models.CharField(blank=True, max_length=50, null=True)),
                ('brandportal_exclusive', models.BooleanField(default=True)),
                ('brandportal_exclusive_open', models.BooleanField(default=True)),
                ('brandportal_show_papercategoy', models.BooleanField(default=True)),
                ('brandportal_show_papercolor', models.BooleanField(default=True)),
                ('brandportal_show_pms_input', models.BooleanField(default=True)),
                ('brandportal_show_orders', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Brandportal',
                'verbose_name_plural': 'Brandportals',
            },
        ),
        migrations.CreateModel(
            name='CheckDomains',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'domains',
                'verbose_name_plural': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'conditions',
                'verbose_name_plural': 'condition',
            },
        ),
        migrations.CreateModel(
            name='DropdownChoices',
            fields=[
                ('dropdown_id', models.AutoField(primary_key=True, serialize=False)),
                ('dropdown', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'dropdowns',
                'verbose_name_plural': 'dropdown',
            },
        ),
        migrations.CreateModel(
            name='DropdownCountries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'countries',
                'verbose_name_plural': 'country',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('event_speaker', models.CharField(blank=True, max_length=200, null=True)),
                ('event_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_time', models.CharField(blank=True, max_length=200, null=True)),
                ('event_host', models.CharField(blank=True, max_length=200, null=True)),
                ('event_location', models.CharField(blank=True, max_length=500, null=True)),
                ('event_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'events',
                'verbose_name_plural': 'event',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'questions',
                'verbose_name_plural': 'question',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.CharField(blank=True, max_length=10000, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'messages',
                'verbose_name_plural': 'message',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('productcategory', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'productcategories',
                'verbose_name_plural': 'productcategory',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'texts',
                'verbose_name_plural': 'text',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('whitelist_id', models.AutoField(primary_key=True, serialize=False)),
                ('whitelist_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'whitelist_texts',
                'verbose_name_plural': 'whitelist_text',
            },
        ),
    ]
