# Generated by Django 5.0.6 on 2024-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPortalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandportal', models.CharField(blank=True, max_length=200)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('brand_payoff', models.CharField(blank=True, max_length=300)),
                ('contact_email', models.CharField(blank=True, max_length=400)),
                ('contact_name', models.CharField(blank=True, max_length=400)),
                ('loc_order_supply', models.CharField(blank=True, max_length=400)),
                ('doc_loc_offer_1', models.CharField(blank=True, max_length=400)),
                ('doc_loc_offer_2', models.CharField(blank=True, max_length=400)),
                ('doc_loc_offer_3', models.CharField(blank=True, max_length=400)),
                ('doc_loc_offer_4', models.CharField(blank=True, max_length=400)),
                ('doc_loc_offer_5', models.CharField(blank=True, max_length=400)),
                ('doc_loc_offer_6', models.CharField(blank=True, max_length=400)),
                ('img_bg_loc_inlog', models.CharField(blank=True, max_length=400)),
                ('img_loc_logo', models.CharField(blank=True, max_length=400)),
                ('img_loc_logo_lg', models.CharField(blank=True, max_length=400)),
                ('img_loc_logo_sm', models.CharField(blank=True, max_length=400)),
                ('img_loc_sheets', models.CharField(blank=True, max_length=400)),
                ('img_loc_plano', models.PositiveIntegerField(default=4)),
                ('img_loc_folders', models.PositiveIntegerField(default=4)),
                ('img_loc_selfcovers', models.PositiveIntegerField(default=4)),
                ('img_loc_brochures', models.PositiveIntegerField(default=4)),
                ('img_loc_envelopes', models.PositiveIntegerField(default=4)),
                ('brandcolor_bg', models.CharField(blank=True, max_length=50)),
                ('brandcolor_font', models.CharField(blank=True, max_length=50)),
                ('brandcolor_header', models.CharField(blank=True, max_length=50)),
                ('brandportal_ordershow', models.BooleanField(default=True)),
                ('brandportal_exclusive', models.BooleanField(default=True)),
                ('brandportal_exclusive_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Brandportal',
                'verbose_name_plural': 'Brandportals',
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'conditions',
                'verbose_name_plural': 'condition',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'questions',
                'verbose_name_plural': 'question',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.CharField(blank=True, max_length=10000, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'messages',
                'verbose_name_plural': 'message',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('productcategory', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'productcategories',
                'verbose_name_plural': 'productcategory',
            },
        ),
    ]
