# Generated by Django 5.0.6 on 2024-05-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_initial'),
        ('profileuseraccount', '0004_remove_members_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownChoices',
            fields=[
                ('dropdown_id', models.AutoField(primary_key=True, serialize=False)),
                ('dropdown', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages')),
            ],
            options={
                'verbose_name': 'dropdowns',
                'verbose_name_plural': 'dropdown',
            },
        ),
    ]
