# Generated by Django 5.1.1 on 2024-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_conditions_options_conditions_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditions',
            old_name='faq_id',
            new_name='condition_id',
        ),
        migrations.AddField(
            model_name='faqs',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
