# Generated by Django 5.0.6 on 2024-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_dropdownchoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandportaldata',
            old_name='brandportal_ordershow',
            new_name='brandportal_show_orders',
        ),
        migrations.AddField(
            model_name='brandportaldata',
            name='brandportal_show_papercategoy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandportaldata',
            name='brandportal_show_papercolor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandportaldata',
            name='brandportal_show_pms_input',
            field=models.BooleanField(default=True),
        ),
    ]
