# Generated by Django 5.1.1 on 2024-11-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_faq_id_conditions_condition_id_faqs_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandPortalData',
        ),
    ]
