# Generated by Django 5.0.6 on 2024-06-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_brandportaldata_img_loc_envelopes_and_more'),
        ('profileuseraccount', '0012_alter_members_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownCountries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages')),
            ],
            options={
                'verbose_name': 'countries',
                'verbose_name_plural': 'country',
            },
        ),
    ]
