# Generated by Django 5.1.1 on 2024-11-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_delete_brandportaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistDomains',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('excluded', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blacklistdomains',
                'verbose_name_plural': 'Blacklistdomain',
            },
        ),
        migrations.CreateModel(
            name='BlacklistEmail',
            fields=[
                ('blacklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('blacklist_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('excluded', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BlacklistsEmails',
                'verbose_name_plural': 'BlacklistEmail',
            },
        ),
        migrations.CreateModel(
            name='WhitelistEmail',
            fields=[
                ('whitelist_id', models.AutoField(primary_key=True, serialize=False)),
                ('whitelist_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('excluded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'whitelist_texts',
                'verbose_name_plural': 'whitelist_text',
            },
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='language',
        ),
        migrations.DeleteModel(
            name='CheckDomains',
        ),
        migrations.RemoveField(
            model_name='whitelist',
            name='language',
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='Whitelist',
        ),
    ]
