# Generated by Django 5.0.6 on 2024-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_dropdowncountries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdowncountries',
            name='value',
        ),
        migrations.AddField(
            model_name='dropdowncountries',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
