# Generated by Django 5.1.1 on 2024-11-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_blacklistdomains_blacklistemail_whitelistemail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistemail',
            options={'verbose_name': 'WhitelistEmails', 'verbose_name_plural': 'WhitelistEmail'},
        ),
        migrations.RenameField(
            model_name='blacklistemail',
            old_name='blacklist_text',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='whitelistemail',
            old_name='whitelist_text',
            new_name='email',
        ),
    ]
