# Generated by Django 5.0.6 on 2024-07-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_dropdowncountries_value_and_more'),
        ('profileuseraccount', '0016_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDomains',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'domains',
                'verbose_name_plural': 'domain',
            },
        ),
        migrations.CreateModel(
            name='MailTexts',
            fields=[
                ('mailtext_id', models.AutoField(primary_key=True, serialize=False)),
                ('mailtext', models.CharField(blank=True, max_length=1000, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages')),
            ],
            options={
                'verbose_name': 'mailtexts',
                'verbose_name_plural': 'mailtext',
            },
        ),
    ]
