# Generated by Django 5.0.6 on 2024-07-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_checkdomains_mailtexts'),
        ('profileuseraccount', '0016_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTexts',
            fields=[
                ('generaltext_id', models.AutoField(primary_key=True, serialize=False)),
                ('generaltext', models.CharField(blank=True, max_length=1000, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages')),
            ],
            options={
                'verbose_name': 'generalists',
                'verbose_name_plural': 'generaltext',
            },
        ),
    ]
