# Generated by Django 5.0.6 on 2024-08-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_generaltexts'),
        ('profileuseraccount', '0017_members_mobile_number_producers_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtexts',
            name='language',
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages')),
            ],
            options={
                'verbose_name': 'texts',
                'verbose_name_plural': 'text',
            },
        ),
        migrations.DeleteModel(
            name='GeneralTexts',
        ),
        migrations.DeleteModel(
            name='MailTexts',
        ),
    ]
