# Generated by Django 5.0.6 on 2024-09-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_remove_mailtexts_language_texts_delete_generaltexts_and_more'),
        ('profileuseraccount', '0017_members_mobile_number_producers_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('blacklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('blacklist_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages')),
            ],
            options={
                'verbose_name': 'blacklist_texts',
                'verbose_name_plural': 'blacklist_text',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('whitelist_id', models.AutoField(primary_key=True, serialize=False)),
                ('whitelist_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages')),
            ],
            options={
                'verbose_name': 'whitelist_texts',
                'verbose_name_plural': 'whitelist_text',
            },
        ),
    ]
