# Generated by Django 5.0.6 on 2024-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_location',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
