# Generated by Django 5.0.6 on 2024-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_events_event_location_events_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_speaker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
