# Generated by Django 5.0.6 on 2024-09-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_events_event_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
