# Generated by Django 5.0.6 on 2024-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureFinishingMethods',
            fields=[
                ('finishingmethod_id', models.AutoField(primary_key=True, serialize=False)),
                ('finishingmethod', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'finishingmethod',
                'verbose_name_plural': 'finishingmethods',
            },
        ),
        migrations.CreateModel(
            name='EnhancementOptions',
            fields=[
                ('enhancement_id', models.AutoField(primary_key=True, serialize=False)),
                ('enhancement', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Enhancement option',
                'verbose_name_plural': 'Enhancement options',
            },
        ),
        migrations.CreateModel(
            name='FoldingMethods',
            fields=[
                ('foldingmethod_id', models.AutoField(primary_key=True, serialize=False)),
                ('foldingmethod', models.TextField(blank=True, max_length=200)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('width_factor', models.PositiveIntegerField(blank=True, null=True)),
                ('height_factor', models.PositiveIntegerField(blank=True, null=True)),
                ('foldingmachine_number_of_stations', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'foldingmethod',
                'verbose_name_plural': 'foldingmethods',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=2500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'notes',
                'verbose_name_plural': 'note',
            },
        ),
        migrations.CreateModel(
            name='PackagingOptions',
            fields=[
                ('packagingoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('packaging', models.CharField(max_length=50)),
                ('packaging_unit', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'packagingoption',
                'verbose_name_plural': 'packaging options',
            },
        ),
        migrations.CreateModel(
            name='StandardSize',
            fields=[
                ('standardsize_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.CharField(blank=True, max_length=50, null=True)),
                ('size_description', models.TextField(blank=True, max_length=200)),
                ('height_mm_product', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm_product', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'standardsizes',
                'verbose_name_plural': 'standardsize',
            },
        ),
        migrations.CreateModel(
            name='TransportOptions',
            fields=[
                ('transportoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport', models.CharField(max_length=50)),
                ('measure', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'transportoption',
                'verbose_name_plural': 'transport options',
            },
        ),
    ]
