# Generated by Django 5.0.6 on 2024-05-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_initial'),
        ('methods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochurefinishingmethods',
            name='productcategory',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.productcategory'),
        ),
    ]
