# Generated by Django 5.0.6 on 2024-05-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_standardsize_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardsize',
            old_name='description',
            new_name='size_description',
        ),
    ]
