# Generated by Django 5.0.6 on 2024-09-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('orderstatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderstatus', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'orderstatus',
                'verbose_name_plural': 'orderstatus',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(blank=True, max_length=200, null=True)),
                ('order_description', models.TextField(blank=True, max_length=1000)),
                ('supplier_remarks', models.TextField(blank=True, max_length=500)),
                ('orderdate', models.DateField(blank=True, null=True)),
                ('order_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('order_morecost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_remarks', models.TextField(blank=True, max_length=300)),
                ('delivery_date_request', models.DateField(blank=True, null=True)),
                ('delivery_date_deliverd', models.DateField(blank=True, null=True)),
                ('printfiles_available', models.CharField(blank=True, max_length=300, null=True)),
                ('deliver_street_number', models.CharField(blank=True, max_length=300, null=True)),
                ('deliver_postcode', models.CharField(blank=True, max_length=300, null=True)),
                ('deliver_city', models.CharField(blank=True, max_length=300, null=True)),
                ('deliver_company', models.CharField(blank=True, max_length=300, null=True)),
                ('deliver_contactperson', models.CharField(blank=True, max_length=300, null=True)),
                ('deliver_tel', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.clients')),
            ],
            options={
                'verbose_name': 'orders',
                'verbose_name_plural': 'order',
            },
        ),
    ]
