# Generated by Django 5.0.6 on 2024-05-09 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProducerMatch',
            fields=[
                ('memberproducermatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('api', models.BooleanField(default=True)),
                ('api_username', models.CharField(blank=True, max_length=100)),
                ('api_password', models.CharField(blank=True, max_length=15)),
                ('producerclient_id', models.CharField(blank=True, max_length=15)),
                ('ranking', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('producer_accept', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'producers',
                'verbose_name_plural': 'producer',
            },
        ),
        migrations.CreateModel(
            name='MemberProducerSalesAllowance',
            fields=[
                ('salesallowance_id', models.AutoField(primary_key=True, serialize=False)),
                ('perc_salesallowance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProducerStatus',
            fields=[
                ('memberproducerstatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('memberproducerstatus', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'memberproducerstatus',
                'verbose_name_plural': 'memberproducerstatus',
            },
        ),
        migrations.CreateModel(
            name='PrintProjectMatch',
            fields=[
                ('printprojectmatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('ranking', models.IntegerField(default=1)),
                ('matchprintproject', models.BooleanField(default=False)),
                ('member_block', models.BooleanField(default=False)),
                ('preferred_supplier', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintProjects',
            fields=[
                ('printproject_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(blank=True, max_length=500, null=True)),
                ('catalog_code', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('error', models.TextField(blank=True, max_length=500)),
                ('message_extra_work', models.TextField(blank=True, max_length=1000)),
                ('own_quotenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('client_quotenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('rfq_date', models.DateTimeField(auto_now_add=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_offers', models.PositiveIntegerField(default=0)),
                ('supply_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('format_selection', models.CharField(blank=True, max_length=200, null=True)),
                ('standard_size', models.CharField(blank=True, max_length=200, null=True)),
                ('height_mm_product', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm_product', models.PositiveIntegerField(blank=True, null=True)),
                ('papercategory', models.CharField(blank=True, max_length=200, null=True)),
                ('paperbrand', models.CharField(blank=True, max_length=200, null=True)),
                ('paperweight', models.PositiveIntegerField(blank=True, null=True)),
                ('papercolor', models.CharField(blank=True, max_length=200, null=True)),
                ('pressvarnish_front', models.PositiveIntegerField(blank=True, null=True)),
                ('pressvarnish_rear', models.PositiveIntegerField(blank=True, null=True)),
                ('pressvarnish_booklet', models.PositiveIntegerField(blank=True, null=True)),
                ('enhance_sided', models.PositiveIntegerField(blank=True, null=True)),
                ('enhance_front', models.PositiveIntegerField(blank=True, null=True)),
                ('enhance_rear', models.PositiveIntegerField(blank=True, null=True)),
                ('packaging', models.CharField(blank=True, max_length=200, null=True)),
                ('folding', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('portrait_landscape', models.PositiveIntegerField(blank=True, null=True)),
                ('finishing_brochures', models.PositiveIntegerField(blank=True, null=True)),
                ('printsided', models.PositiveIntegerField(blank=True, null=True)),
                ('number_pms_colors_front', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('number_pms_colors_rear', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('number_pms_colors_booklet', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('print_front', models.PositiveIntegerField(blank=True, null=True)),
                ('print_rear', models.PositiveIntegerField(blank=True, null=True)),
                ('print_booklet', models.PositiveIntegerField(blank=True, null=True)),
                ('papercategory_cover', models.CharField(blank=True, max_length=200, null=True)),
                ('paperbrand_cover', models.CharField(blank=True, max_length=200, null=True)),
                ('paperweight_cover', models.PositiveIntegerField(blank=True, null=True)),
                ('papercolor_cover', models.CharField(blank=True, max_length=200, null=True)),
                ('salesprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salesprice_1000extra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoiceturnover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('assortiment_item', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'printprojects',
                'verbose_name_plural': 'printproject',
            },
        ),
        migrations.CreateModel(
            name='PrintprojectStatus',
            fields=[
                ('printprojectstatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('printprojectstatus', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'printprojectstatus',
                'verbose_name_plural': 'printprojectstatus',
            },
        ),
    ]
