# Generated by Django 5.0.6 on 2024-05-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0002_initial'),
        ('profileuseraccount', '0004_remove_members_expire_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberproducersalesallowance',
            options={'verbose_name': 'salesallowance', 'verbose_name_plural': 'salesallowance'},
        ),
        migrations.AddField(
            model_name='memberproducerstatus',
            name='language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.languages'),
        ),
        migrations.AddField(
            model_name='memberproducerstatus',
            name='status_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memberproducerstatus',
            name='memberproducerstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberproducerstatus',
            name='memberproducerstatus_id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
