# Generated by Django 5.0.6 on 2024-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0003_alter_memberproducersalesallowance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberproducermatch',
            name='producerclient_id',
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='member_accept',
            field=models.BooleanField(default=True),
        ),
    ]
