# Generated by Django 5.1.1 on 2024-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0003_memberproducermatch_auto_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printprojects',
            name='enhance_front',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='enhance_rear',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='finishing_brochures',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='folding',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='portrait_landscape',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='pressvarnish_booklet',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='pressvarnish_front',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='pressvarnish_rear',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='print_booklet',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='print_front',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='print_rear',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='printsided',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='volume',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
