# Generated by Django 5.1.1 on 2024-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0004_alter_printprojects_enhance_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printprojects',
            name='enhance_sided',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='number_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='paperweight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
