# Generated by Django 5.0.6 on 2024-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0004_remove_memberproducermatch_producerclient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberproducermatch',
            name='perc_salesallowance_9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='MemberProducerSalesAllowance',
        ),
    ]
