# Generated by Django 5.1.1 on 2024-11-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0005_alter_printprojects_enhance_sided_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printprojects',
            old_name='enhance_rear',
            new_name='enhance_back',
        ),
        migrations.RenameField(
            model_name='printprojects',
            old_name='number_pms_colors_rear',
            new_name='number_pms_colors_back',
        ),
        migrations.RenameField(
            model_name='printprojects',
            old_name='pressvarnish_rear',
            new_name='pressvarnish_back',
        ),
        migrations.RenameField(
            model_name='printprojects',
            old_name='print_rear',
            new_name='print_back',
        ),
    ]
