# Generated by Django 5.1.1 on 2024-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0006_rename_enhance_rear_printprojects_enhance_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printprojects',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printprojects',
            name='supply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
