# Generated by Django 5.1.1 on 2024-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0007_alter_printprojects_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printprojects',
            name='description',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
