# Generated by Django 5.1.1 on 2024-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0009_alter_printprojectmatch_printproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printprojects',
            name='env_category_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='printprojects',
            name='env_material_color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='printprojects',
            name='env_size_close_cut',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='printprojects',
            name='env_window',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
