# Generated by Django 5.1.1 on 2024-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printprojects', '0010_printprojects_env_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printprojects',
            name='env_category_name',
        ),
        migrations.AddField(
            model_name='printprojects',
            name='env_category_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
