# Generated by Django 5.0.6 on 2024-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContacts',
            fields=[
                ('clientcontact_id', models.AutoField(primary_key=True, serialize=False)),
                ('clientcontact', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=25)),
                ('e_mail_personal', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('manager', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'clientcontacts',
                'verbose_name_plural': 'clientcontact',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100, unique=True)),
                ('tel_general', models.CharField(blank=True, max_length=15)),
                ('e_mail_general', models.EmailField(blank=True, max_length=254)),
                ('street_number', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=7)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('manager_first_name', models.CharField(blank=True, max_length=200)),
                ('manager_last_name', models.CharField(blank=True, max_length=200)),
                ('manager_jobtitle', models.CharField(blank=True, max_length=200)),
                ('manager_mobile_number', models.CharField(blank=True, max_length=100)),
                ('manager_e_mail', models.CharField(blank=True, max_length=100)),
                ('count_printprojects', models.PositiveIntegerField(default=0)),
                ('count_orders', models.PositiveIntegerField(default=0)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'clients',
                'verbose_name_plural': 'client',
            },
        ),
        migrations.CreateModel(
            name='MemberProducerStatus',
            fields=[
                ('memberproducerstatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('memberproducerstatus', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'memberproducerstatus',
                'verbose_name_plural': 'memberproducerstatus',
            },
        ),
    ]
