# Generated by Django 5.0.6 on 2024-05-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberplans',
            old_name='plan_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='memberplans',
            old_name='memberplan_id',
            new_name='member_plan_id',
        ),
        migrations.RemoveField(
            model_name='memberplans',
            name='memberplan',
        ),
        migrations.RemoveField(
            model_name='producers',
            name='productcategories',
        ),
        migrations.AddField(
            model_name='memberplans',
            name='producer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producers',
            name='member_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuseraccount.memberplans'),
        ),
    ]
