# Generated by Django 5.0.6 on 2024-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0002_rename_plan_id_memberplans_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='producer',
            new_name='exclusive',
        ),
        migrations.AddField(
            model_name='members',
            name='producerplan',
            field=models.BooleanField(default=False),
        ),
    ]
