# Generated by Django 5.1.1 on 2024-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0002_producers_e_mail_offers_producers_e_mail_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='members',
            name='tel_general',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='producers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='producers',
            name='tel_general',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tel_general',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
