# Generated by Django 5.0.6 on 2024-05-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0003_rename_producer_members_exclusive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='expire_date',
        ),
    ]
