# Generated by Django 5.1.1 on 2024-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0003_alter_members_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='producer_application',
            field=models.BooleanField(default=False),
        ),
    ]
