# Generated by Django 5.1.1 on 2024-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0004_userprofile_producer_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='only_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
