# Generated by Django 5.0.6 on 2024-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0004_remove_members_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producers',
            old_name='api_available',
            new_name='api_active',
        ),
        migrations.RemoveField(
            model_name='members',
            name='city',
        ),
        migrations.RemoveField(
            model_name='members',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='producers',
            name='facebook_url',
        ),
        migrations.AddField(
            model_name='members',
            name='country_code',
            field=models.CharField(default='NL', max_length=100),
        ),
        migrations.AddField(
            model_name='producers',
            name='api_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producers',
            name='calculation_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producers',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producers',
            name='exclusive_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(default='NL', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
