# Generated by Django 5.1.1 on 2024-11-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0005_producers_only_exclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producers',
            name='brandportal_module',
        ),
        migrations.RemoveField(
            model_name='producers',
            name='exclusive_module',
        ),
    ]
