# Generated by Django 5.0.6 on 2024-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0005_rename_api_available_producers_api_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producers',
            name='country',
        ),
        migrations.AddField(
            model_name='producers',
            name='country_code',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='country_code',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
