# Generated by Django 5.0.6 on 2024-06-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0006_remove_producers_country_producers_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
