# Generated by Django 5.0.6 on 2024-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0007_members_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='brandportal_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producers',
            name='powerplatform_module',
            field=models.BooleanField(default=False),
        ),
    ]
