# Generated by Django 5.0.6 on 2024-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0008_producers_brandportal_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
