# Generated by Django 5.0.6 on 2024-06-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0009_producers_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='url',
            new_name='company_url',
        ),
        migrations.RenameField(
            model_name='producers',
            old_name='linkedin_url',
            new_name='company_url',
        ),
        migrations.RemoveField(
            model_name='producers',
            name='url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
