# Generated by Django 5.0.6 on 2024-06-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0010_rename_url_members_company_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='exclusive',
        ),
    ]
