# Generated by Django 5.0.6 on 2024-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0011_remove_members_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='country_code',
            field=models.CharField(default='NL', max_length=100),
        ),
        migrations.AlterField(
            model_name='producers',
            name='country_code',
            field=models.CharField(default='NL', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(default='NL', max_length=100),
        ),
    ]
