# Generated by Django 5.0.6 on 2024-06-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0012_alter_members_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='demo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='demo',
        ),
    ]
