# Generated by Django 5.0.6 on 2024-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuseraccount', '0016_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='producers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='conditions_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='city',
            field=models.CharField(blank=True, default='Amersfoort', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='members',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='street_number',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='producers',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='producers',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='producers',
            name='e_mail_general',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='producers',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='producers',
            name='street_number',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='producers',
            name='tel_general',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_number',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
